name: "mnist_pytorch_pt"
platform: "pytorch_libtorch"
max_batch_size: 16
input [
    {
        name: "input__0"
        data_type: TYPE_FP32
        format: FORMAT_NCHW
        dims: [1, 28, 28]
    }
]
output [
    {
        name: "output__0"
        data_type: TYPE_FP32
        dims: [1, 10]
    }
]
