name: "mnist_tf_savedmodel"
platform: "tensorflow_savedmodel"
max_batch_size: 32
input [
    {
        name: "flatten_1_input"
        data_type: TYPE_FP32
        format: FORMAT_NHWC
        dims: [28, 28, 1]
    }
]
output [
    {
        name: "dense_3"
        data_type: TYPE_FP32
        dims: [10]
    }
]
